package simpledb.execution;

import simpledb.transaction.TransactionAbortedException;
import simpledb.common.DbException;
import simpledb.storage.Tuple;
import simpledb.storage.TupleDesc;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;

    private JoinPredicate jp;
    private OpIterator child1;
    private OpIterator child2;
    private JoinMethod joinMethod = JoinMethod.NESTED_LOOP; // default method
    private Tuple outerTuple = null; // current tuple in outer table

    public enum JoinMethod {
        NESTED_LOOP,
        BLOCK_NESTED_LOOP,
    }

    public void setJoinMethod(JoinMethod method) {
        this.joinMethod = method;
    }

    /**
     * Constructor. Accepts two children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, OpIterator child1, OpIterator child2) {
        // some code goes here
        this.jp = p;
        this.child1 = child1;
        this.child2 = child2;
    }

    public JoinPredicate getJoinPredicate() {
        // some code goes here
        return this.jp;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        // some code goes here
        return child1.getTupleDesc().getFieldName(jp.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        // some code goes here
        return child1.getTupleDesc().getFieldName(jp.getField2());
    }

    /**
     * @see TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // some code goes here
        return TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());
    }
    

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // some code goes here
        super.open();
        child1.open();
        child2.open();
    }

    public void close() {
        // some code goes here
        child1.close();
        child2.close();
        super.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // some code goes here
        child1.rewind();
        child2.rewind();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // some code goes here
        switch (joinMethod) {
            case NESTED_LOOP:
                return nestedLoopNext();
            case BLOCK_NESTED_LOOP:
                return blockNestedLoopNext();
            default:
                throw new DbException("Unknown join method");
        }
    }

    private Tuple nestedLoopNext() throws TransactionAbortedException, DbException {
        // Should not call child1.rewind()
        while (true) {
            if (outerTuple == null) {
                // finished scanning the outer table
                if (!child1.hasNext()) return null;
                outerTuple = child1.next();
                child2.rewind();
            }
            
            while (child2.hasNext()) {
                Tuple innerTuple = child2.next();
                if (jp.filter(outerTuple, innerTuple)) {
                    Tuple joinedTuple = Tuple.mergeTuples(outerTuple, innerTuple);
                    return joinedTuple;
                } else {
                    continue;
                }
            }
            // finihsed scanning inner table for current outer tuple, move to next
            this.outerTuple = null;
        }
    }




    private Tuple blockNestedLoopNext() throws TransactionAbortedException, DbException {
        // Implement block nested loop join logic here
        return null;
    }

    @Override
    public OpIterator[] getChildren() {
        // some code goes here
        return new OpIterator[]{this.child1, this.child2};
    }

    @Override
    public void setChildren(OpIterator[] children) {
        // some code goes here
        if (children.length != 2) {
            throw new IllegalArgumentException("Join operator requires two children");
        }
        this.child1 = children[0];
        this.child2 = children[1];
    }

}
